/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'theme' : string,
  'downloadQuality' : string,
  'passengerId' : string,
}
export interface AudioTrack {
  'id' : string,
  'audioLabel' : string,
  'langCode' : string,
  'language' : string,
  'isDefault' : boolean,
}
export interface DownloadedItem {
  'id' : string,
  'title' : string,
  'expiresAt' : bigint,
  'album' : string,
  'tags' : Array<string>,
  'artworkUrl' : string,
  'downloadedAt' : bigint,
  'language' : string,
  'genre' : string,
  'passengerId' : string,
  'mediaType' : string,
  'artist' : string,
}
export interface Passenger {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'tripId' : string,
  'role' : string,
}
export interface StudioMusic {
  'id' : string,
  'title' : string,
  'duration' : string,
  'album' : string,
  'isPublished' : boolean,
  'language' : string,
  'genre' : string,
  'artist' : string,
  'coverArt' : string,
  'dateAdded' : bigint,
}
export interface StudioVideo {
  'id' : string,
  'title' : string,
  'audioTracks' : Array<AudioTrack>,
  'duration' : string,
  'hlsMasterUrl' : string,
  'processingStatus' : string,
  'isPublished' : boolean,
  'ageRating' : string,
  'description' : string,
  'genre' : string,
  'posterUrl' : string,
  'primaryLanguage' : string,
  'dateAdded' : bigint,
}
export interface _SERVICE {
  'addAudioTrack' : ActorMethod<[string, AudioTrack], undefined>,
  'addDownload' : ActorMethod<[DownloadedItem], undefined>,
  'createPassenger' : ActorMethod<[string, string, string, string], undefined>,
  'createStudioMusic' : ActorMethod<[StudioMusic], undefined>,
  'createStudioVideo' : ActorMethod<[StudioVideo], undefined>,
  'deleteDownload' : ActorMethod<[string], undefined>,
  'deleteStudioMusic' : ActorMethod<[string], undefined>,
  'deleteStudioVideo' : ActorMethod<[string], undefined>,
  'getDownloads' : ActorMethod<[string], Array<DownloadedItem>>,
  'getPassenger' : ActorMethod<[string], Passenger>,
  'getSettings' : ActorMethod<[string], [] | [AppSettings]>,
  'getStudioMusic' : ActorMethod<[string], StudioMusic>,
  'getStudioVideo' : ActorMethod<[string], StudioVideo>,
  'listPassengers' : ActorMethod<[], Array<Passenger>>,
  'listStudioMusic' : ActorMethod<[], Array<StudioMusic>>,
  'listStudioVideos' : ActorMethod<[], Array<StudioVideo>>,
  'removeAudioTrack' : ActorMethod<[string, string], undefined>,
  'renewDownload' : ActorMethod<[string, bigint], undefined>,
  'saveSettings' : ActorMethod<[string, string, string], undefined>,
  'searchDownloads' : ActorMethod<
    [string, string, [] | [string]],
    Array<DownloadedItem>
  >,
  'setDefaultAudioTrack' : ActorMethod<[string, string], undefined>,
  'updateStudioMusic' : ActorMethod<
    [string, string, string, string, string, string, string, boolean],
    undefined
  >,
  'updateStudioVideo' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    undefined
  >,
  'validateManagerKey' : ActorMethod<[string], boolean>,
  'validateStaffKey' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];