/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'theme' : string,
  'downloadQuality' : string,
  'passengerId' : string,
}
export interface DownloadedItem {
  'id' : string,
  'title' : string,
  'expiresAt' : bigint,
  'album' : string,
  'tags' : Array<string>,
  'artworkUrl' : string,
  'downloadedAt' : bigint,
  'language' : string,
  'genre' : string,
  'passengerId' : string,
  'mediaType' : string,
  'artist' : string,
}
export interface Passenger {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'tripId' : string,
  'role' : string,
}
export interface _SERVICE {
  'addDownload' : ActorMethod<[DownloadedItem], undefined>,
  'createPassenger' : ActorMethod<[string, string, string, string], undefined>,
  'deleteDownload' : ActorMethod<[string], undefined>,
  'getDownloads' : ActorMethod<[string], Array<DownloadedItem>>,
  'getPassenger' : ActorMethod<[string], Passenger>,
  'getSettings' : ActorMethod<[string], [] | [AppSettings]>,
  'listPassengers' : ActorMethod<[], Array<Passenger>>,
  'renewDownload' : ActorMethod<[string, bigint], undefined>,
  'saveSettings' : ActorMethod<[string, string, string], undefined>,
  'searchDownloads' : ActorMethod<
    [string, string, [] | [string]],
    Array<DownloadedItem>
  >,
  'validateStaffKey' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];