/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DownloadedItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'expiresAt' : IDL.Int,
  'album' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'artworkUrl' : IDL.Text,
  'downloadedAt' : IDL.Int,
  'language' : IDL.Text,
  'genre' : IDL.Text,
  'passengerId' : IDL.Text,
  'mediaType' : IDL.Text,
  'artist' : IDL.Text,
});
export const Passenger = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'tripId' : IDL.Text,
  'role' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'theme' : IDL.Text,
  'downloadQuality' : IDL.Text,
  'passengerId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDownload' : IDL.Func([DownloadedItem], [], []),
  'createPassenger' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteDownload' : IDL.Func([IDL.Text], [], []),
  'getDownloads' : IDL.Func([IDL.Text], [IDL.Vec(DownloadedItem)], ['query']),
  'getPassenger' : IDL.Func([IDL.Text], [Passenger], ['query']),
  'getSettings' : IDL.Func([IDL.Text], [IDL.Opt(AppSettings)], ['query']),
  'listPassengers' : IDL.Func([], [IDL.Vec(Passenger)], ['query']),
  'renewDownload' : IDL.Func([IDL.Text, IDL.Int], [], []),
  'saveSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'searchDownloads' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Vec(DownloadedItem)],
      [],
    ),
  'validateStaffKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DownloadedItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'expiresAt' : IDL.Int,
    'album' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'artworkUrl' : IDL.Text,
    'downloadedAt' : IDL.Int,
    'language' : IDL.Text,
    'genre' : IDL.Text,
    'passengerId' : IDL.Text,
    'mediaType' : IDL.Text,
    'artist' : IDL.Text,
  });
  const Passenger = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'tripId' : IDL.Text,
    'role' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'theme' : IDL.Text,
    'downloadQuality' : IDL.Text,
    'passengerId' : IDL.Text,
  });
  
  return IDL.Service({
    'addDownload' : IDL.Func([DownloadedItem], [], []),
    'createPassenger' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteDownload' : IDL.Func([IDL.Text], [], []),
    'getDownloads' : IDL.Func([IDL.Text], [IDL.Vec(DownloadedItem)], ['query']),
    'getPassenger' : IDL.Func([IDL.Text], [Passenger], ['query']),
    'getSettings' : IDL.Func([IDL.Text], [IDL.Opt(AppSettings)], ['query']),
    'listPassengers' : IDL.Func([], [IDL.Vec(Passenger)], ['query']),
    'renewDownload' : IDL.Func([IDL.Text, IDL.Int], [], []),
    'saveSettings' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'searchDownloads' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Vec(DownloadedItem)],
        [],
      ),
    'validateStaffKey' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };