/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Passenger {
    id: string;
    name: string;
    createdAt: bigint;
    tripId: string;
    role: string;
}
export interface AppSettings {
    theme: string;
    downloadQuality: string;
    passengerId: string;
}
export interface DownloadedItem {
    id: string;
    title: string;
    expiresAt: bigint;
    album: string;
    tags: Array<string>;
    artworkUrl: string;
    downloadedAt: bigint;
    language: string;
    genre: string;
    passengerId: string;
    mediaType: string;
    artist: string;
}
export interface AudioTrack {
    id: string;
    audioLabel: string;
    langCode: string;
    language: string;
    isDefault: boolean;
}
export interface StudioMusic {
    id: string;
    title: string;
    duration: string;
    album: string;
    isPublished: boolean;
    language: string;
    genre: string;
    artist: string;
    coverArt: string;
    dateAdded: bigint;
}
export interface StudioVideo {
    id: string;
    title: string;
    audioTracks: Array<AudioTrack>;
    duration: string;
    hlsMasterUrl: string;
    processingStatus: string;
    isPublished: boolean;
    ageRating: string;
    description: string;
    genre: string;
    posterUrl: string;
    primaryLanguage: string;
    dateAdded: bigint;
}
export interface backendInterface {
    addAudioTrack(videoId: string, track: AudioTrack): Promise<void>;
    addDownload(item: DownloadedItem): Promise<void>;
    createPassenger(id: string, name: string, role: string, tripId: string): Promise<void>;
    createStudioMusic(music: StudioMusic): Promise<void>;
    createStudioVideo(video: StudioVideo): Promise<void>;
    deleteDownload(id: string): Promise<void>;
    deleteStudioMusic(id: string): Promise<void>;
    deleteStudioVideo(id: string): Promise<void>;
    getDownloads(passengerId: string): Promise<Array<DownloadedItem>>;
    getPassenger(passengerId: string): Promise<Passenger>;
    getSettings(passengerId: string): Promise<AppSettings | null>;
    getStudioMusic(id: string): Promise<StudioMusic>;
    getStudioVideo(id: string): Promise<StudioVideo>;
    listPassengers(): Promise<Array<Passenger>>;
    listStudioMusic(): Promise<Array<StudioMusic>>;
    listStudioVideos(): Promise<Array<StudioVideo>>;
    removeAudioTrack(videoId: string, trackId: string): Promise<void>;
    renewDownload(id: string, newExpiresAt: bigint): Promise<void>;
    saveSettings(passengerId: string, theme: string, downloadQuality: string): Promise<void>;
    searchDownloads(passengerId: string, searchTerm: string, typeFilter: string | null): Promise<Array<DownloadedItem>>;
    setDefaultAudioTrack(videoId: string, trackId: string): Promise<void>;
    updateStudioMusic(id: string, title: string, artist: string, album: string, genre: string, language: string, coverArt: string, isPublished: boolean): Promise<void>;
    updateStudioVideo(id: string, title: string, description: string, genre: string, ageRating: string, primaryLanguage: string, posterUrl: string, hlsMasterUrl: string, processingStatus: string, isPublished: boolean): Promise<void>;
    validateManagerKey(key: string): Promise<boolean>;
    validateStaffKey(key: string): Promise<boolean>;
}
import type { AppSettings as _AppSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAudioTrack(arg0: string, arg1: AudioTrack): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAudioTrack(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAudioTrack(arg0, arg1);
            return result;
        }
    }
    async addDownload(arg0: DownloadedItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDownload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDownload(arg0);
            return result;
        }
    }
    async createPassenger(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPassenger(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPassenger(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createStudioMusic(arg0: StudioMusic): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudioMusic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudioMusic(arg0);
            return result;
        }
    }
    async createStudioVideo(arg0: StudioVideo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudioVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudioVideo(arg0);
            return result;
        }
    }
    async deleteDownload(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDownload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDownload(arg0);
            return result;
        }
    }
    async deleteStudioMusic(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudioMusic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudioMusic(arg0);
            return result;
        }
    }
    async deleteStudioVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudioVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudioVideo(arg0);
            return result;
        }
    }
    async getDownloads(arg0: string): Promise<Array<DownloadedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDownloads(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDownloads(arg0);
            return result;
        }
    }
    async getPassenger(arg0: string): Promise<Passenger> {
        if (this.processError) {
            try {
                const result = await this.actor.getPassenger(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPassenger(arg0);
            return result;
        }
    }
    async getSettings(arg0: string): Promise<AppSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudioMusic(arg0: string): Promise<StudioMusic> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudioMusic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudioMusic(arg0);
            return result;
        }
    }
    async getStudioVideo(arg0: string): Promise<StudioVideo> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudioVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudioVideo(arg0);
            return result;
        }
    }
    async listPassengers(): Promise<Array<Passenger>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPassengers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPassengers();
            return result;
        }
    }
    async listStudioMusic(): Promise<Array<StudioMusic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudioMusic();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudioMusic();
            return result;
        }
    }
    async listStudioVideos(): Promise<Array<StudioVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listStudioVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listStudioVideos();
            return result;
        }
    }
    async removeAudioTrack(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAudioTrack(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAudioTrack(arg0, arg1);
            return result;
        }
    }
    async renewDownload(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renewDownload(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renewDownload(arg0, arg1);
            return result;
        }
    }
    async saveSettings(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(arg0, arg1, arg2);
            return result;
        }
    }
    async searchDownloads(arg0: string, arg1: string, arg2: string | null): Promise<Array<DownloadedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDownloads(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDownloads(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async setDefaultAudioTrack(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultAudioTrack(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultAudioTrack(arg0, arg1);
            return result;
        }
    }
    async updateStudioMusic(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudioMusic(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudioMusic(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateStudioVideo(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudioVideo(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudioVideo(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async validateManagerKey(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateManagerKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateManagerKey(arg0);
            return result;
        }
    }
    async validateStaffKey(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateStaffKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateStaffKey(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppSettings]): AppSettings | null {
    return value.length === 0 ? null : value[0];
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
