import type {
  Album,
  Artist,
  MusicTrack,
  Playlist,
  StudioMusic,
  StudioVideo,
  VideoContent,
} from "./types";

// ─── Video Content ────────────────────────────────────────────────────────────

export const mockVideos: VideoContent[] = [
  {
    id: "v1",
    title: "Stellar Odyssey",
    year: 2024,
    rating: "PG-13",
    runtime: "2h 18m",
    genre: "Sci-Fi",
    language: "English",
    description:
      "A crew of interstellar explorers ventures beyond the known galaxy, discovering civilizations that challenge everything humanity thought it understood about the cosmos. An epic journey of survival, wonder, and first contact.",
    posterUrl: "https://picsum.photos/seed/v1stellar/300/450",
    backdropUrl: "https://picsum.photos/seed/v1stellar_back/800/450",
    subtitles: ["English", "Spanish", "French", "German"],
    resumePosition: 1823,
    tags: ["space", "exploration", "aliens"],
    hlsMasterUrl: "/media/videos/v1/master.m3u8",
    defaultAudioLang: "en",
    audioTracks: [
      {
        id: "at1",
        language: "English",
        langCode: "en",
        audioLabel: "Stereo",
        isDefault: true,
      },
      {
        id: "at2",
        language: "Spanish",
        langCode: "es",
        audioLabel: "Stereo",
        isDefault: false,
      },
      {
        id: "at3",
        language: "French",
        langCode: "fr",
        audioLabel: "Stereo",
        isDefault: false,
      },
    ],
  },
  {
    id: "v2",
    title: "Gravity's Edge",
    year: 2023,
    rating: "PG-13",
    runtime: "1h 52m",
    genre: "Action",
    language: "English",
    description:
      "When a catastrophic satellite collision leaves two astronauts adrift in orbit, they must fight against impossible odds and dwindling oxygen to survive. A tense, breathtaking thriller set among the stars.",
    posterUrl: "https://picsum.photos/seed/v2gravity/300/450",
    backdropUrl: "https://picsum.photos/seed/v2gravity_back/800/450",
    subtitles: ["English", "Japanese", "Korean"],
    resumePosition: 0,
    tags: ["survival", "space", "thriller"],
    hlsMasterUrl: "/media/videos/v2/master.m3u8",
    defaultAudioLang: "en",
    audioTracks: [
      {
        id: "at4",
        language: "English",
        langCode: "en",
        audioLabel: "Stereo",
        isDefault: true,
      },
      {
        id: "at5",
        language: "Japanese",
        langCode: "ja",
        audioLabel: "Stereo",
        isDefault: false,
      },
    ],
  },
  {
    id: "v3",
    title: "The Red Planet Chronicles",
    year: 2024,
    rating: "TV-MA",
    runtime: "1h 30m",
    genre: "Documentary",
    language: "English",
    description:
      "An intimate documentary following the first permanent Mars colony through its tumultuous first year. Stunning cinematography captures the raw beauty of the Martian landscape and the human spirit.",
    posterUrl: "https://picsum.photos/seed/v3mars/300/450",
    backdropUrl: "https://picsum.photos/seed/v3mars_back/800/450",
    subtitles: ["English", "Spanish"],
    tags: ["mars", "documentary", "science"],
    hlsMasterUrl: "/media/videos/v3/master.m3u8",
    defaultAudioLang: "en",
    audioTracks: [
      {
        id: "at6",
        language: "English",
        langCode: "en",
        audioLabel: "Stereo",
        isDefault: true,
      },
      {
        id: "at7",
        language: "Spanish",
        langCode: "es",
        audioLabel: "Stereo",
        isDefault: false,
      },
    ],
  },
  {
    id: "v4",
    title: "Dark Matter",
    year: 2023,
    rating: "R",
    runtime: "2h 05m",
    genre: "Drama",
    language: "English",
    description:
      "A quantum physicist wakes in a world that isn't his own, forced to navigate a labyrinth of alternate realities to find his way home. A mind-bending thriller about choice, identity, and the roads not taken.",
    posterUrl: "https://picsum.photos/seed/v4dark/300/450",
    backdropUrl: "https://picsum.photos/seed/v4dark_back/800/450",
    subtitles: ["English", "French", "German", "Italian"],
    resumePosition: 3240,
    tags: ["quantum", "thriller", "parallel worlds"],
  },
  {
    id: "v5",
    title: "Nebula Station",
    year: 2024,
    rating: "TV-14",
    runtime: "45m",
    genre: "Sci-Fi",
    language: "English",
    description:
      "Life aboard humanity's most remote space station gets complicated when a mysterious signal from deep space triggers a chain of events that could reshape the fate of the human race.",
    posterUrl: "https://picsum.photos/seed/v5nebula/300/450",
    backdropUrl: "https://picsum.photos/seed/v5nebula_back/800/450",
    subtitles: ["English", "Spanish", "Mandarin"],
    tags: ["station", "signal", "mystery"],
  },
  {
    id: "v6",
    title: "Zero Gravity Comedy Club",
    year: 2023,
    rating: "TV-14",
    runtime: "1h 20m",
    genre: "Comedy",
    language: "English",
    description:
      "Five comedians perform stand-up in actual microgravity conditions aboard a parabolic flight. Hilarity, chaos, and unexpected profundity ensue as jokes and comedians float freely.",
    posterUrl: "https://picsum.photos/seed/v6comedy/300/450",
    backdropUrl: "https://picsum.photos/seed/v6comedy_back/800/450",
    subtitles: ["English"],
    tags: ["comedy", "standup", "weightless"],
  },
  {
    id: "v7",
    title: "The Last Mission",
    year: 2022,
    rating: "PG-13",
    runtime: "2h 32m",
    genre: "Action",
    language: "English",
    description:
      "A veteran astronaut on the verge of retirement is called for one final mission when a rogue AI threatens to destroy Earth's entire satellite network. The race against time begins.",
    posterUrl: "https://picsum.photos/seed/v7mission/300/450",
    backdropUrl: "https://picsum.photos/seed/v7mission_back/800/450",
    subtitles: ["English", "Spanish", "French"],
    tags: ["action", "ai", "satellites"],
  },
  {
    id: "v8",
    title: "Proxima",
    year: 2024,
    rating: "PG",
    runtime: "1h 47m",
    genre: "Drama",
    language: "French",
    description:
      "A French astronaut prepares for a year-long mission to the International Space Station while balancing the profound weight of leaving her young daughter behind on Earth.",
    posterUrl: "https://picsum.photos/seed/v8proxima/300/450",
    backdropUrl: "https://picsum.photos/seed/v8proxima_back/800/450",
    subtitles: ["French", "English", "German"],
    tags: ["family", "emotional", "iss"],
  },
  {
    id: "v9",
    title: "Asteroid Hunters",
    year: 2023,
    rating: "G",
    runtime: "52m",
    genre: "Documentary",
    language: "English",
    description:
      "Follow the scientists and astronomers who track near-Earth asteroids 24 hours a day, working to protect our planet from potentially devastating impacts.",
    posterUrl: "https://picsum.photos/seed/v9asteroid/300/450",
    backdropUrl: "https://picsum.photos/seed/v9asteroid_back/800/450",
    subtitles: ["English"],
    tags: ["asteroids", "science", "protection"],
  },
  {
    id: "v10",
    title: "Exoplanet Dreams",
    year: 2024,
    rating: "PG",
    runtime: "1h 15m",
    genre: "Documentary",
    language: "English",
    description:
      "A visually stunning journey through the most extraordinary exoplanets ever discovered, from lava worlds and ice giants to planets with two suns where the skies never go dark.",
    posterUrl: "https://picsum.photos/seed/v10exo/300/450",
    backdropUrl: "https://picsum.photos/seed/v10exo_back/800/450",
    subtitles: ["English", "Spanish", "Japanese"],
    tags: ["exoplanets", "planets", "discovery"],
  },
];

// ─── Music Tracks ─────────────────────────────────────────────────────────────

export const mockTracks: MusicTrack[] = [
  {
    id: "t1",
    title: "Cosmic Drift",
    artist: "Luna Vera",
    album: "Stellar Dreams",
    albumArt: "https://picsum.photos/seed/t1cosmic/300/300",
    duration: 247,
    genre: "Electronic",
    year: 2024,
  },
  {
    id: "t2",
    title: "Solar Winds",
    artist: "The Astronauts",
    album: "Beyond the Horizon",
    albumArt: "https://picsum.photos/seed/t2solar/300/300",
    duration: 198,
    genre: "Indie",
    year: 2023,
  },
  {
    id: "t3",
    title: "Orbit 7",
    artist: "Nova Collective",
    album: "Deep Space Sessions",
    albumArt: "https://picsum.photos/seed/t3orbit/300/300",
    duration: 312,
    genre: "Ambient",
    year: 2024,
  },
  {
    id: "t4",
    title: "Event Horizon",
    artist: "Luna Vera",
    album: "Stellar Dreams",
    albumArt: "https://picsum.photos/seed/t4event/300/300",
    duration: 278,
    genre: "Electronic",
    year: 2024,
  },
  {
    id: "t5",
    title: "Pale Blue Dot",
    artist: "Cosmos Echo",
    album: "Messages From Earth",
    albumArt: "https://picsum.photos/seed/t5pale/300/300",
    duration: 325,
    genre: "Acoustic",
    year: 2023,
  },
  {
    id: "t6",
    title: "Interstellar",
    artist: "The Astronauts",
    album: "Beyond the Horizon",
    albumArt: "https://picsum.photos/seed/t6inter/300/300",
    duration: 421,
    genre: "Orchestral",
    year: 2023,
  },
  {
    id: "t7",
    title: "Pulsar Beat",
    artist: "Nova Collective",
    album: "Deep Space Sessions",
    albumArt: "https://picsum.photos/seed/t7pulsar/300/300",
    duration: 189,
    genre: "Electronic",
    year: 2024,
  },
  {
    id: "t8",
    title: "Neptune Rising",
    artist: "Astral Plains",
    album: "Outer Realms",
    albumArt: "https://picsum.photos/seed/t8neptune/300/300",
    duration: 268,
    genre: "Ambient",
    year: 2022,
  },
  {
    id: "t9",
    title: "Gravity Well",
    artist: "Cosmos Echo",
    album: "Messages From Earth",
    albumArt: "https://picsum.photos/seed/t9gravity/300/300",
    duration: 304,
    genre: "Indie",
    year: 2023,
  },
  {
    id: "t10",
    title: "Starfall",
    artist: "Luna Vera",
    album: "Midnight Launch",
    albumArt: "https://picsum.photos/seed/t10starfall/300/300",
    duration: 233,
    genre: "Pop",
    year: 2024,
  },
  {
    id: "t11",
    title: "Space Cadet",
    artist: "The Astronauts",
    album: "Beyond the Horizon",
    albumArt: "https://picsum.photos/seed/t11space/300/300",
    duration: 215,
    genre: "Rock",
    year: 2023,
  },
  {
    id: "t12",
    title: "Andromeda",
    artist: "Astral Plains",
    album: "Outer Realms",
    albumArt: "https://picsum.photos/seed/t12andro/300/300",
    duration: 356,
    genre: "Orchestral",
    year: 2022,
  },
  {
    id: "t13",
    title: "Dark Side",
    artist: "Nova Collective",
    album: "Deep Space Sessions",
    albumArt: "https://picsum.photos/seed/t13dark/300/300",
    duration: 291,
    genre: "Ambient",
    year: 2024,
  },
  {
    id: "t14",
    title: "Moonrise",
    artist: "Cosmos Echo",
    album: "Messages From Earth",
    albumArt: "https://picsum.photos/seed/t14moon/300/300",
    duration: 178,
    genre: "Acoustic",
    year: 2023,
  },
  {
    id: "t15",
    title: "Launch Day",
    artist: "Luna Vera",
    album: "Midnight Launch",
    albumArt: "https://picsum.photos/seed/t15launch/300/300",
    duration: 195,
    genre: "Pop",
    year: 2024,
  },
  {
    id: "t16",
    title: "Thermosphere",
    artist: "Astral Plains",
    album: "Outer Realms",
    albumArt: "https://picsum.photos/seed/t16thermo/300/300",
    duration: 442,
    genre: "Orchestral",
    year: 2022,
  },
  {
    id: "t17",
    title: "Ion Storm",
    artist: "The Astronauts",
    album: "Solar Flare EP",
    albumArt: "https://picsum.photos/seed/t17ion/300/300",
    duration: 223,
    genre: "Rock",
    year: 2024,
  },
  {
    id: "t18",
    title: "Void Walk",
    artist: "Nova Collective",
    album: "Deep Space Sessions",
    albumArt: "https://picsum.photos/seed/t18void/300/300",
    duration: 387,
    genre: "Ambient",
    year: 2024,
  },
  {
    id: "t19",
    title: "Terraforming",
    artist: "Cosmos Echo",
    album: "New Worlds",
    albumArt: "https://picsum.photos/seed/t19terra/300/300",
    duration: 261,
    genre: "Electronic",
    year: 2024,
  },
  {
    id: "t20",
    title: "Zero G",
    artist: "Luna Vera",
    album: "Midnight Launch",
    albumArt: "https://picsum.photos/seed/t20zerog/300/300",
    duration: 204,
    genre: "Pop",
    year: 2024,
  },
];

// ─── Playlists ────────────────────────────────────────────────────────────────

export const mockPlaylists: Playlist[] = [
  {
    id: "p1",
    name: "Mission Control Mix",
    coverArt: "https://picsum.photos/seed/p1mission/300/300",
    trackCount: 24,
    description: "Essential tracks for long-haul spaceflight",
    tracks: ["t1", "t3", "t6", "t8", "t12"],
  },
  {
    id: "p2",
    name: "Weightless Focus",
    coverArt: "https://picsum.photos/seed/p2weight/300/300",
    trackCount: 18,
    description: "Ambient soundscapes for deep concentration",
    tracks: ["t3", "t8", "t13", "t18"],
  },
  {
    id: "p3",
    name: "Launch Day Hype",
    coverArt: "https://picsum.photos/seed/p3launch/300/300",
    trackCount: 15,
    description: "High-energy tracks to fuel your countdown",
    tracks: ["t2", "t7", "t11", "t15", "t17"],
  },
  {
    id: "p4",
    name: "Stargazing Sessions",
    coverArt: "https://picsum.photos/seed/p4star/300/300",
    trackCount: 20,
    description: "Chill beats for watching the cosmos",
    tracks: ["t1", "t5", "t9", "t14", "t20"],
  },
  {
    id: "p5",
    name: "Solar System Tour",
    coverArt: "https://picsum.photos/seed/p5solar/300/300",
    trackCount: 30,
    description: "A musical journey across all eight planets",
    tracks: ["t6", "t8", "t12", "t16"],
  },
];

// ─── Albums ───────────────────────────────────────────────────────────────────

export const mockAlbums: Album[] = [
  {
    id: "a1",
    title: "Stellar Dreams",
    artist: "Luna Vera",
    coverArt: "https://picsum.photos/seed/a1stellar/300/300",
    year: 2024,
    trackCount: 12,
  },
  {
    id: "a2",
    title: "Beyond the Horizon",
    artist: "The Astronauts",
    coverArt: "https://picsum.photos/seed/a2beyond/300/300",
    year: 2023,
    trackCount: 10,
  },
  {
    id: "a3",
    title: "Deep Space Sessions",
    artist: "Nova Collective",
    coverArt: "https://picsum.photos/seed/a3deep/300/300",
    year: 2024,
    trackCount: 14,
  },
  {
    id: "a4",
    title: "Messages From Earth",
    artist: "Cosmos Echo",
    coverArt: "https://picsum.photos/seed/a4messages/300/300",
    year: 2023,
    trackCount: 11,
  },
  {
    id: "a5",
    title: "Outer Realms",
    artist: "Astral Plains",
    coverArt: "https://picsum.photos/seed/a5outer/300/300",
    year: 2022,
    trackCount: 9,
  },
];

// ─── Artists ──────────────────────────────────────────────────────────────────

export const mockArtists: Artist[] = [
  {
    id: "ar1",
    name: "Luna Vera",
    imageUrl: "https://picsum.photos/seed/ar1luna/300/300",
    genre: "Electronic / Pop",
    followerCount: 2840000,
  },
  {
    id: "ar2",
    name: "The Astronauts",
    imageUrl: "https://picsum.photos/seed/ar2astro/300/300",
    genre: "Indie / Rock",
    followerCount: 1920000,
  },
  {
    id: "ar3",
    name: "Nova Collective",
    imageUrl: "https://picsum.photos/seed/ar3nova/300/300",
    genre: "Electronic / Ambient",
    followerCount: 1340000,
  },
  {
    id: "ar4",
    name: "Cosmos Echo",
    imageUrl: "https://picsum.photos/seed/ar4cosmos/300/300",
    genre: "Acoustic / Indie",
    followerCount: 890000,
  },
  {
    id: "ar5",
    name: "Astral Plains",
    imageUrl: "https://picsum.photos/seed/ar5astral/300/300",
    genre: "Orchestral / Ambient",
    followerCount: 650000,
  },
  {
    id: "ar6",
    name: "Midnight Launch",
    imageUrl: "https://picsum.photos/seed/ar6midnight/300/300",
    genre: "Pop / Synth",
    followerCount: 420000,
  },
];

// ─── Helper: format duration ──────────────────────────────────────────────────

export function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

export function formatFollowers(count: number): string {
  if (count >= 1_000_000) return `${(count / 1_000_000).toFixed(1)}M`;
  if (count >= 1_000) return `${(count / 1_000).toFixed(0)}K`;
  return count.toString();
}

// ─── Studio Seed Data ─────────────────────────────────────────────────────────

export const seedStudioVideos: StudioVideo[] = [
  {
    id: "sv1",
    title: "Stellar Odyssey",
    description:
      "A crew of interstellar explorers ventures beyond the known galaxy.",
    genre: "Sci-Fi",
    ageRating: "PG-13",
    primaryLanguage: "English",
    posterUrl: "https://picsum.photos/seed/v1stellar/300/450",
    hlsMasterUrl: "/media/videos/sv1/master.m3u8",
    processingStatus: "ready",
    isPublished: true,
    duration: "2h 18m",
    dateAdded: Date.now() - 7 * 24 * 60 * 60 * 1000,
    audioTracks: [
      {
        id: "sat1",
        language: "English",
        langCode: "en",
        audioLabel: "Stereo",
        isDefault: true,
      },
      {
        id: "sat2",
        language: "Spanish",
        langCode: "es",
        audioLabel: "Stereo",
        isDefault: false,
      },
      {
        id: "sat3",
        language: "French",
        langCode: "fr",
        audioLabel: "Stereo",
        isDefault: false,
      },
    ],
    subtitles: [
      { id: "ss1", language: "English", langCode: "en" },
      { id: "ss2", language: "Spanish", langCode: "es" },
    ],
  },
  {
    id: "sv2",
    title: "Gravity's Edge",
    description: "Two astronauts fight impossible odds to survive in orbit.",
    genre: "Action",
    ageRating: "PG-13",
    primaryLanguage: "English",
    posterUrl: "https://picsum.photos/seed/v2gravity/300/450",
    hlsMasterUrl: "/media/videos/sv2/master.m3u8",
    processingStatus: "ready",
    isPublished: true,
    duration: "1h 52m",
    dateAdded: Date.now() - 14 * 24 * 60 * 60 * 1000,
    audioTracks: [
      {
        id: "sat4",
        language: "English",
        langCode: "en",
        audioLabel: "Stereo",
        isDefault: true,
      },
      {
        id: "sat5",
        language: "Japanese",
        langCode: "ja",
        audioLabel: "Stereo",
        isDefault: false,
      },
    ],
    subtitles: [{ id: "ss3", language: "English", langCode: "en" }],
  },
  {
    id: "sv3",
    title: "Dark Matter",
    description:
      "A physicist navigates alternate realities to find his way home.",
    genre: "Drama",
    ageRating: "R",
    primaryLanguage: "English",
    posterUrl: "https://picsum.photos/seed/v4dark/300/450",
    hlsMasterUrl: "/media/videos/sv3/master.m3u8",
    processingStatus: "unpublished",
    isPublished: false,
    duration: "2h 05m",
    dateAdded: Date.now() - 3 * 24 * 60 * 60 * 1000,
    audioTracks: [
      {
        id: "sat6",
        language: "English",
        langCode: "en",
        audioLabel: "Stereo",
        isDefault: true,
      },
    ],
    subtitles: [],
  },
];

export const seedStudioMusic: StudioMusic[] = [
  {
    id: "sm1",
    title: "Cosmic Drift",
    artist: "Luna Vera",
    album: "Stellar Dreams",
    genre: "Electronic",
    language: "Instrumental",
    coverArt: "https://picsum.photos/seed/t1cosmic/300/300",
    dateAdded: Date.now() - 5 * 24 * 60 * 60 * 1000,
    duration: "4:07",
    isPublished: true,
  },
  {
    id: "sm2",
    title: "Solar Winds",
    artist: "The Astronauts",
    album: "Beyond the Horizon",
    genre: "Indie",
    language: "English",
    coverArt: "https://picsum.photos/seed/t2solar/300/300",
    dateAdded: Date.now() - 10 * 24 * 60 * 60 * 1000,
    duration: "3:18",
    isPublished: true,
  },
  {
    id: "sm3",
    title: "Void Walk",
    artist: "Nova Collective",
    album: "Deep Space Sessions",
    genre: "Ambient",
    language: "Instrumental",
    coverArt: "https://picsum.photos/seed/t18void/300/300",
    dateAdded: Date.now() - 2 * 24 * 60 * 60 * 1000,
    duration: "6:27",
    isPublished: false,
  },
];
